# Data

https://github.com/observablehq/sample-datasets/blob/main/aapl.csv

In [1]:
# Numerical arrays.
import numpy as np

# Data frames.
import pandas as pd

## Reading CSV Files in NumPy

https://numpy.org/doc/stable/user/how-to-io.html

https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy-loadtxt

In [2]:
# Read data from a CSV using numpy.
data = np.loadtxt("../data/aapl.csv", skiprows=1, delimiter=",", usecols=(1, 2, 3, 4, 5, 6))

# Have a look.
data

array([[6.45014270e+01, 6.54142840e+01, 6.45000000e+01, 6.49628600e+01,
        5.09616280e+01, 7.92372000e+07],
       [6.48357160e+01, 6.50285720e+01, 6.31642880e+01, 6.34085730e+01,
        4.97423290e+01, 1.11779500e+08],
       [6.27371440e+01, 6.30000000e+01, 6.03371430e+01, 6.12642860e+01,
        4.80601880e+01, 1.85403400e+08],
       ...,
       [1.86550003e+02, 1.87399994e+02, 1.85220001e+02, 1.87360001e+02,
        1.86640305e+02, 2.32112000e+07],
       [1.87740005e+02, 1.90369995e+02, 1.87649994e+02, 1.90039993e+02,
        1.89309998e+02, 2.79893000e+07],
       [1.89490005e+02, 1.90059998e+02, 1.87449997e+02, 1.88589996e+02,
        1.88589996e+02, 2.58066000e+07]], shape=(1260, 6))

## Slicing

https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing

In [3]:
# The first row.
data[0]

array([6.4501427e+01, 6.5414284e+01, 6.4500000e+01, 6.4962860e+01,
       5.0961628e+01, 7.9237200e+07])

In [4]:
# The first column.
data[:, 0]

array([ 64.501427,  64.835716,  62.737144, ..., 186.550003, 187.740005,
       189.490005], shape=(1260,))

## Read CSV in Pandas

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [5]:
# Very simple.
df = pd.read_csv("../data/aapl.csv")

In [6]:
# Show.
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-05-13,64.501427,65.414284,64.500000,64.962860,50.961628,79237200
1,2013-05-14,64.835716,65.028572,63.164288,63.408573,49.742329,111779500
2,2013-05-15,62.737144,63.000000,60.337143,61.264286,48.060188,185403400
3,2013-05-16,60.462856,62.549999,59.842857,62.082859,48.702328,150801000
4,2013-05-17,62.721428,62.869999,61.572857,61.894287,48.554409,106976100
...,...,...,...,...,...,...,...
1255,2018-05-07,185.179993,187.669998,184.750000,185.160004,184.448746,42451400
1256,2018-05-08,184.990005,186.220001,183.669998,186.050003,185.335327,28402800
1257,2018-05-09,186.550003,187.399994,185.220001,187.360001,186.640305,23211200
1258,2018-05-10,187.740005,190.369995,187.649994,190.039993,189.309998,27989300
1259,2018-05-11,189.490005,190.059998,187.449997,188.589996,188.589996,25806600

In [7]:
# Read directly from a URL.
df = pd.read_csv("https://raw.githubusercontent.com/observablehq/sample-datasets/refs/heads/main/aapl.csv")

In [8]:
# Show.
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-05-13,64.501427,65.414284,64.500000,64.962860,50.961628,79237200
1,2013-05-14,64.835716,65.028572,63.164288,63.408573,49.742329,111779500
2,2013-05-15,62.737144,63.000000,60.337143,61.264286,48.060188,185403400
3,2013-05-16,60.462856,62.549999,59.842857,62.082859,48.702328,150801000
4,2013-05-17,62.721428,62.869999,61.572857,61.894287,48.554409,106976100
...,...,...,...,...,...,...,...
1255,2018-05-07,185.179993,187.669998,184.750000,185.160004,184.448746,42451400
1256,2018-05-08,184.990005,186.220001,183.669998,186.050003,185.335327,28402800
1257,2018-05-09,186.550003,187.399994,185.220001,187.360001,186.640305,23211200
1258,2018-05-10,187.740005,190.369995,187.649994,190.039993,189.309998,27989300
1259,2018-05-11,189.490005,190.059998,187.449997,188.589996,188.589996,25806600

## End